=== ewjmulder/program-your-home/voice-control/src/main/resources/com/programyourhome/config/voice-control/xsd/voice-control.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://programyourhome.com/config/voice-control" targetNamespace="http://programyourhome.com/config/voice-control"
    elementFormDefault="qualified">
    <xsd:element name="voiceControlConfig">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="languages" type="languages" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="languages">
        <xsd:sequence>
            <xsd:element name="language" type="language" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="language">
        <xsd:sequence>
            <xsd:element name="id" type="id" minOccurs="1" maxOccurs="1" />
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="locale" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="confirmations" type="confirmations" minOccurs="1" maxOccurs="1" />
            <xsd:element name="negations" type="negations" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="id">
        <xsd:restriction base="xsd:unsignedShort" />
    </xsd:simpleType>
    <xsd:complexType name="confirmations">
        <xsd:sequence>
            <xsd:element name="confirmation" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="negations">
        <xsd:sequence>
            <xsd:element name="negation" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ewjmulder/program-your-home/voice-control/src/main/resources/com/programyourhome/config/voice-control/xml/voice-control.xml
<?xml version="1.0" encoding="UTF-8"?>
<voiceControlConfig xmlns="http://programyourhome.com/config/voice-control" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://programyourhome.com/config/voice-control ../xsd/voice-control.xsd">
    <languages>
        <language>
            <id>1</id>
            <name>English USA</name>
            <locale>en-us</locale>
            <confirmations>
                <confirmation>yes</confirmation>
                <confirmation>yep</confirmation>
                <confirmation>yeah</confirmation>
            </confirmations>
            <negations>
                <negation>no</negation>
                <negation>nope</negation>
            </negations>
        </language>
        <language>
            <id>2</id>
            <name>English UK</name>
            <locale>en-uk</locale>
            <confirmations>
                <confirmation>yes</confirmation>
                <confirmation>yep</confirmation>
                <confirmation>yeah</confirmation>
            </confirmations>
            <negations>
                <negation>no</negation>
                <negation>nope</negation>
            </negations>
        </language>
        <language>
            <id>3</id>
            <name>Dutch NL</name>
            <locale>nl-nl</locale>
            <confirmations>
                <confirmation>ja</confirmation>
                <confirmation>jah</confirmation>
                <confirmation>yes</confirmation>
                <confirmation>jes</confirmation>
                <confirmation>yep</confirmation>
                <confirmation>jep</confirmation>
                <confirmation>yeah</confirmation>
                <confirmation>yup</confirmation>
                <confirmation>jup</confirmation>
            </confirmations>
            <negations>
                <negation>nee</negation>
                <negation>neen</negation>
                <negation>no</negation>
                <negation>nope</negation>
            </negations>
        </language>
    </languages>
</voiceControlConfig>
