=== ewjmulder/program-your-home/infra-red/src/main/resources/com/programyourhome/config/infra-red/xsd/infra-red.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://programyourhome.com/config/infra-red" targetNamespace="http://programyourhome.com/config/infra-red"
    elementFormDefault="qualified">
    <xsd:element name="infraRedConfig">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="devices" type="devices" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="devices">
        <xsd:sequence>
            <xsd:element name="device" type="device" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="device">
        <xsd:sequence>
            <xsd:element name="id" type="id" />
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="description" type="xsd:string" />
            <xsd:element name="defaultDelay" type="delay" />
            <xsd:element name="prototypes" type="prototypes" />
            <xsd:element name="remote" type="remote" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="prototypes">
        <xsd:sequence>
            <xsd:element name="power" type="xsd:boolean" />
            <xsd:element name="input" type="xsd:boolean" />
            <xsd:element name="volume" type="xsd:boolean" />
            <xsd:element name="channel" type="xsd:boolean" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="remote">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="keyMapping" type="keyMapping" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="keyMapping">
        <xsd:annotation>
            <xsd:documentation>Both key groups and 'separate' keys can be listed under the key mapping of a remote.</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="keyGroups" type="keyGroups" minOccurs="0" />
            <xsd:element name="keys" type="keys" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="keyGroups">
        <xsd:sequence>
            <xsd:element name="keyGroup" type="keyGroup" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="keyGroup">
        <xsd:annotation>
            <xsd:documentation>
                A key group can be used to put a logical set of keys together under a name.
                Furthermore, every group can default the values of
                type and delay for all keys specified under that group.
                For instance, now you can easily create a group for all channel keys and give them a
                certain appropriate delay.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="groupType" type="keyType" />
            <xsd:element name="groupDelay" type="delay" />
            <xsd:element name="keys" type="keys" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="keys">
        <xsd:sequence>
            <xsd:element name="key" type="key" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="key">
        <xsd:sequence>
            <xsd:element name="id" type="id" />
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="winlircName" type="xsd:string" />
            <xsd:element name="type" type="keyType" minOccurs="0" />
            <xsd:element name="delay" type="delay" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="id">
        <xsd:restriction base="xsd:unsignedShort" />
    </xsd:simpleType>
    <xsd:simpleType name="delay">
        <xsd:restriction base="xsd:unsignedInt">
            <xsd:annotation>
                <xsd:documentation>
                    Delay is the amount of milliseconds to pause after 'pressing' this key, before pressing the next key on the same remote.
                    This is required for functions that take some time on the device before it is responsive again, like powering on.
                    If not specified for a key individually, the required default value for the whole device will be used.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="keyType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="power"></xsd:enumeration>
            <xsd:enumeration value="input"></xsd:enumeration>
            <xsd:enumeration value="volumeUp"></xsd:enumeration>
            <xsd:enumeration value="volumeDown"></xsd:enumeration>
            <xsd:enumeration value="volumeMute"></xsd:enumeration>
            <xsd:enumeration value="channel0"></xsd:enumeration>
            <xsd:enumeration value="channel1"></xsd:enumeration>
            <xsd:enumeration value="channel2"></xsd:enumeration>
            <xsd:enumeration value="channel3"></xsd:enumeration>
            <xsd:enumeration value="channel4"></xsd:enumeration>
            <xsd:enumeration value="channel5"></xsd:enumeration>
            <xsd:enumeration value="channel6"></xsd:enumeration>
            <xsd:enumeration value="channel7"></xsd:enumeration>
            <xsd:enumeration value="channel8"></xsd:enumeration>
            <xsd:enumeration value="channel9"></xsd:enumeration>
            <xsd:enumeration value="channelUp"></xsd:enumeration>
            <xsd:enumeration value="channelDown"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== ewjmulder/program-your-home/infra-red/src/main/resources/com/programyourhome/config/infra-red/xml/infra-red.xml
<?xml version="1.0" encoding="UTF-8"?>
<infraRedConfig xmlns="http://programyourhome.com/config/infra-red" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://programyourhome.com/config/infra-red ../xsd/infra-red.xsd">
    <devices>
        <device>
            <id>1</id>
            <name>Tuner</name>
            <description>Main tuner for all audio and video throughput</description>
            <defaultDelay>100</defaultDelay>
            <prototypes>
                <power>true</power>
                <input>true</input>
                <volume>true</volume>
                <channel>false</channel>
            </prototypes>
            <remote>
                <name>YAMAHA-RAV338-MAIN-ZONE</name>
                <keyMapping>
                    <keys>
                        <key>
                            <id>1</id>
                            <name>Power</name>
                            <winlircName>POWER</winlircName>
                            <type>power</type>
                            <delay>2000</delay>
                        </key>
                        <key>
                            <id>2</id>
                            <name>Volume Up</name>
                            <winlircName>VOLUME_UP</winlircName>
                            <type>volumeUp</type>
                        </key>
                        <key>
                            <id>3</id>
                            <name>Volume Down</name>
                            <winlircName>VOLUME_DOWN</winlircName>
                            <type>volumeDown</type>
                        </key>
                        <key>
                            <id>4</id>
                            <name>Mute</name>
                            <winlircName>VOLUME_MUTE</winlircName>
                            <type>volumeMute</type>
                        </key>
                        <key>
                            <id>5</id>
                            <name>HDMI 1</name>
                            <winlircName>INPUT_HDMI1</winlircName>
                            <type>input</type>
                            <delay>500</delay>
                        </key>
                    </keys>
                </keyMapping>
            </remote>
        </device>
        <device>
            <id>2</id>
            <name>Tuner Kitchen</name>
            <description>Kitchen tuner for audio signal to kitchen speaker</description>
            <defaultDelay>100</defaultDelay>
            <prototypes>
                <power>true</power>
                <input>true</input>
                <volume>true</volume>
                <channel>false</channel>
            </prototypes>
            <remote>
                <name>YAMAHA-RAV338-ZONE2</name>
                <keyMapping>
                    <keys>
                        <key>
                            <id>1</id>
                            <name>Power</name>
                            <winlircName>POWER</winlircName>
                            <type>power</type>
                            <delay>1000</delay>
                        </key>
                        <key>
                            <id>2</id>
                            <name>Volume Up</name>
                            <winlircName>VOLUME_UP</winlircName>
                            <type>volumeUp</type>
                        </key>
                        <key>
                            <id>3</id>
                            <name>Volume Down</name>
                            <winlircName>VOLUME_DOWN</winlircName>
                            <type>volumeDown</type>
                        </key>
                        <key>
                            <id>4</id>
                            <name>Mute</name>
                            <winlircName>VOLUME_MUTE</winlircName>
                            <type>volumeMute</type>
                        </key>
                        <key>
                            <id>5</id>
                            <name>AV 5</name>
                            <winlircName>INPUT_AV5</winlircName>
                            <type>input</type>
                        </key>
                    </keys>
                </keyMapping>
            </remote>
        </device>
        <device>
            <id>3</id>
            <name>TV</name>
            <description>Television screen</description>
            <defaultDelay>200</defaultDelay>
            <prototypes>
                <power>true</power>
                <input>false</input> <!-- TODO: how to process input selection on tv if there is no direct key for it? (could be simulated of course)
                If simulated: find a way to configure it here, since there is no other way to get that input -->
                <volume>true</volume>
                <channel>true</channel>
            </prototypes>
            <remote>
                <name>SAMSUNG-BN59-00685A</name>
                <keyMapping>
                    <keys>
                        <key>
                            <id>1</id>
                            <name>Power</name>
                            <winlircName>POWER</winlircName>
                            <type>power</type>
                            <delay>5000</delay>
                        </key>
                        <key>
                            <id>2</id>
                            <name>Volume Up</name>
                            <winlircName>VOLUME_UP</winlircName>
                            <type>volumeUp</type>
                        </key>
                        <key>
                            <id>3</id>
                            <name>Volume Down</name>
                            <winlircName>VOLUME_DOWN</winlircName>
                            <type>volumeDown</type>
                        </key>
                        <key>
                            <id>4</id>
                            <name>Mute</name>
                            <winlircName>VOLUME_MUTE</winlircName>
                            <type>volumeMute</type>
                        </key>
                    </keys>
                </keyMapping>
            </remote>
        </device>
        <device>
            <id>4</id>
            <name>ITV</name>
            <description>Interactive TV receiver</description>
            <defaultDelay>200</defaultDelay>
            <prototypes>
                <power>true</power>
                <input>false</input>
                <volume>false</volume>
                <channel>true</channel>
            </prototypes>
            <remote>
                <name>MOTOROLA-VIP1853</name>
                <keyMapping>
                    <keys>
                        <key>
                            <id>1</id>
                            <name>Power</name>
                            <winlircName>POWER</winlircName>
                            <type>power</type>
                            <delay>2000</delay>
                        </key>
                    </keys>
                </keyMapping>
            </remote>
        </device>
        <device>
            <id>5</id>
            <name>DVD Player</name>
            <description>Harddisk recorder and DVD player</description>
            <defaultDelay>200</defaultDelay>
            <prototypes>
                <power>true</power>
                <input>false</input> <!-- TODO: how to process input selection on player if there is no direct key for it? (could be simulated maybe?) Check working of Logitech remote for this -->
                <volume>false</volume>
                <channel>false</channel>
            </prototypes>
            <remote>
                <name>PANASONIC-EUR7659Y60</name>
                <keyMapping>
                    <keys>
                        <key>
                            <id>1</id>
                            <name>Power</name>
                            <winlircName>POWER</winlircName>
                            <type>power</type>
                            <delay>2000</delay>
                        </key>
                    </keys>
                </keyMapping>
            </remote>
        </device>
    </devices>
</infraRedConfig>
